export const listOfSentences = [
  "(child noises in the bg)",
  "Hello, hello?",
  "I need to jump in another call",
  "Can everyone go on mute?",
  "Could u please got close to the mic?",
  "(load pain echo feedback)",
  "Next slide please.",
  "Can we take this offline?",
  "Is ___ on the call?",
  "Could u share this afterwards?",
  "Can sb grant presenter rights?",
  "Can u email that to everyone?",
  "Sorry, I have problems in logging in",
  "(animal noises in the bg)",
  "Sorry, I didn't find the conf id",
  "I was having connection issue",
  "I'll have to get back to u",
  "Who just joined?",
  "Sorry, sth ___ with my calender",
  "Do u see my screen?",
  "Let's wait for ___!",
  "u will send the minutes",
  "Sorry, I was on mute.",
  "Can u repeat please?",
];
